/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Applications */
        get: operations["applications_api_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/human": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Human */
        get: operations["human_api_human_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer
         * @description Answer a waiting question once; the engine reuses it on every form and re-queues the job.
         */
        post: operations["answer_api_answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Drafts
         * @description Answers the engine drafted from the Fact Bank and sent without waiting, newest first.
         */
        get: operations["drafts_api_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outcomes */
        get: operations["outcomes_api_outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/narration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Narration */
        get: operations["narration_api_narration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proof/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proof
         * @description A proof screenshot, by file name only (no paths), from workspace/proof.
         */
        get: operations["proof_api_proof__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description SSE: `narration` for each new event, `snapshot` when anything changes (and every 15 s as a keep-alive).
         */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph
         * @description The engine's memory as a graph: You -> lanes -> applications -> companies, facts used, questions answered,
         *     outcomes, ATS (engine/memory/graph.py; same model as engine/memory/schema.cypher).
         */
        get: operations["graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerIn
         * @description One answer typed in the web app for a question the engine could not answer.
         */
        AnswerIn: {
            /** Job */
            job: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** AnswerOut */
        AnswerOut: {
            /** Pattern */
            pattern: string;
            /** Answer */
            answer: string;
            /** Source */
            source: string;
        };
        /**
         * Application
         * @description Latest state of one job (later events win).
         */
        Application: {
            /** Job */
            job: string;
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Ts */
            ts: string;
            /** Url */
            url?: string | null;
            /** Lane */
            lane?: string | null;
            /**
             * Proof
             * @description Proof screenshot path, only when the file exists on disk
             */
            proof?: string | null;
            /** Resume */
            resume?: string | null;
            /**
             * Facts
             * @description Fact Bank ids the resume was built from
             */
            facts?: string[];
            /**
             * Answers
             * @description Question -> answer, as submitted
             */
            answers?: [
                string,
                string | null
            ][];
            /** Detail */
            detail?: string | null;
        };
        /**
         * Drafted
         * @description An answer the engine drafted from Fact Bank entries and sent without waiting (for review).
         */
        Drafted: {
            /** Ts */
            ts: string;
            /** Job */
            job?: string | null;
            /** Status */
            status: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Facts */
            facts?: string[];
        };
        /**
         * Event
         * @description One line of workspace/events.jsonl, with the fields every consumer relies on lifted out.
         */
        Event: {
            /**
             * Id
             * @description Position in the log (1-based); stable because the log is append-only
             */
            id: number;
            /** Ts */
            ts: string;
            /** Kind */
            kind: string;
            /** Job */
            job?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Data
             * @description The full original event
             */
            data?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HumanItem
         * @description Something only the user can do (each job's latest status, never stale history).
         */
        HumanItem: {
            /** Job */
            job: string;
            /** Status */
            status: string;
            /** Text */
            text: string;
            /** Url */
            url?: string | null;
            /** Resume */
            resume?: string | null;
            /**
             * Missing
             * @description Questions the engine could not answer (answer them via POST /api/answers)
             */
            missing?: string[];
        };
        /**
         * Narration
         * @description An event as one plain-English sentence (engine.live.server.narrate).
         */
        Narration: {
            /** Id */
            id: number;
            /** Ts */
            ts?: string | null;
            /**
             * Stage
             * @enum {string}
             */
            stage: "listen" | "judge" | "write" | "apply" | "hear";
            /**
             * Tone
             * @enum {string}
             */
            tone: "calm" | "quiet" | "win" | "you" | "alarm";
            /** Text */
            text: string;
            /** Verified */
            verified?: boolean | null;
        };
        /** Outcome */
        Outcome: {
            /** Ts */
            ts: string;
            /** Company */
            company?: string | null;
            /** Outcome */
            outcome: string;
            /** Subject */
            subject?: string | null;
            /** Jobs */
            jobs?: string[];
        };
        /** Snapshot */
        Snapshot: {
            /** Verified */
            verified: number;
            /** Verified Today */
            verified_today: number;
            /** Waiting */
            waiting: number;
            /** Boards */
            boards: number;
            /** Last Poll */
            last_poll?: number | null;
            /** By Lane */
            by_lane?: {
                [key: string]: number;
            };
            /** Outcomes */
            outcomes?: {
                [key: string]: number;
            };
            /**
             * Backend
             * @enum {string}
             */
            backend: "postgres" | "jsonl";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    snapshot_api_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    applications_api_applications_get: {
        parameters: {
            query?: {
                /** @description SUBMITTED, NEEDS YOU, FAILED, FLAGGED, SKIPPED */
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    human_api_human_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanItem"][];
                };
            };
        };
    };
    answer_api_answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drafts_api_drafts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drafted"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outcomes_api_outcomes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Outcome"][];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                after?: number;
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    narration_api_narration_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Narration"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proof_api_proof__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_api_graph_get: {
        parameters: {
            query?: {
                questions?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
